name: golangci-lint
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: [1.22.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0

